CREATE DATABASE ng_sis_db;
USE ng_sis_db;
CREATE TABLE product(
id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(180),
priceB INT(11),
priceS INT(11),
stock INT(11),
recibo VARCHAR(300),
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
description VARCHAR(300),
category INT(11)
);
CREATE TABLE client(
id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(180),
company VARCHAR(300),
direccion VARCHAR(300),
provin VARCHAR(300),
tel VARCHAR(300),
tel2 VARCHAR(300),
email VARCHAR(300),
courrier VARCHAR(300),
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
codigo VARCHAR(300),
img VARCHAR(300)
);
CREATE TABLE provider(
id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(180),
company VARCHAR(300),
direccion VARCHAR(300),
tel VARCHAR(300),
tel2 VARCHAR(300),
email VARCHAR(300),
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
provider VARCHAR(300)
);
CREATE TABLE category(
id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(180),
description VARCHAR(300),
);


DESCRIBE product;